% 专业系统详细信息界面 V4.0
% 重新设计的全息曝光系统详细信息界面
% 版权所有 © 个人Z.Y团队Y.M
% 更新日期：2024年12月31日

function ProfessionalSystemInfoGUI()
    % 创建专业的系统信息界面
    
    % 创建主窗口
    infoFig = figure('Name', '全息曝光系统详细信息 - 专业版', ...
        'Position', [100, 100, 1200, 800], ...
        'NumberTitle', 'off', 'MenuBar', 'none', 'Resize', 'on', ...
        'Color', [0.95 0.95 0.95]);
    
    % 创建标签页组
    tabGroup = uitabgroup(infoFig, 'Position', [0.02, 0.02, 0.96, 0.96]);
    
    % 标签页1: 基本显示参数
    tab1 = uitab(tabGroup, 'Title', '基本显示参数', 'BackgroundColor', [0.98 0.98 0.98]);
    createBasicParamsTab(tab1);
    
    % 标签页2: 光栅物理参数
    tab2 = uitab(tabGroup, 'Title', '光栅物理参数', 'BackgroundColor', [0.98 0.98 0.98]);
    createGratingParamsTab(tab2);
    
    % 标签页3: SLM硬件参数
    tab3 = uitab(tabGroup, 'Title', 'SLM硬件参数', 'BackgroundColor', [0.98 0.98 0.98]);
    createSLMParamsTab(tab3);
    
    % 标签页4: 曝光系统分析
    tab4 = uitab(tabGroup, 'Title', '曝光系统分析', 'BackgroundColor', [0.98 0.98 0.98]);
    createExposureAnalysisTab(tab4);
end

function createBasicParamsTab(parent)
    % 创建基本参数标签页
    
    % 标题
    uicontrol(parent, 'Style', 'text', 'String', '基本显示参数', ...
        'Position', [50, 720, 300, 30], 'FontSize', 16, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.98 0.98 0.98], 'ForegroundColor', [0.2 0.2 0.7]);
    
    % 参数显示区域
    paramPanel = uipanel(parent, 'Title', '当前系统参数', ...
        'Position', [0.05, 0.4, 0.4, 0.5], 'FontSize', 12, ...
        'BackgroundColor', [0.98 0.98 0.98]);
    
    % 参数文本
    paramText = sprintf(['分辨率: 1920 × 1200 像素\n', ...
        '像素尺寸: 8.0 μm\n', ...
        '物理尺寸: 15.360 mm × 9.600 mm\n', ...
        '对角线尺寸: 0.7 英寸\n', ...
        '长宽比: 16:10\n', ...
        '实际物理尺寸: %.2f mm²\n', ...
        '图像像素总数: %.2f 百万像素\n', ...
        '曝光光斑: 大光斑 (7mm) / 小光斑 (2.5mm)\n', ...
        '照射波长: 450.0 nm'], ...
        15.360 * 9.600, 1920 * 1200 / 1e6);
    
    uicontrol(paramPanel, 'Style', 'text', 'String', paramText, ...
        'Position', [10, 10, 350, 280], 'FontSize', 11, ...
        'HorizontalAlignment', 'left', 'BackgroundColor', [0.98 0.98 0.98]);
    
    % 曝光范围分析
    analysisPanel = uipanel(parent, 'Title', '曝光范围分析', ...
        'Position', [0.05, 0.05, 0.9, 0.3], 'FontSize', 12, ...
        'BackgroundColor', [0.98 0.98 0.98]);
    
    % 分析文本
    analysisText = sprintf(['曝光范围分析:\n\n', ...
        '图像宽度方向覆盖率: 45.6%%\n', ...
        '图像高度方向覆盖率: 72.9%%\n', ...
        '有效曝光区域: 38.48 mm²\n', ...
        '图像总面积: 147.46 mm²\n', ...
        '曝光面积覆盖率: 26.1%%']);
    
    uicontrol(analysisPanel, 'Style', 'text', 'String', analysisText, ...
        'Position', [20, 20, 300, 140], 'FontSize', 11, ...
        'HorizontalAlignment', 'left', 'BackgroundColor', [0.98 0.98 0.98]);
end

function createGratingParamsTab(parent)
    % 创建光栅参数标签页
    
    % 标题
    uicontrol(parent, 'Style', 'text', 'String', '光栅物理参数与公式', ...
        'Position', [50, 720, 400, 30], 'FontSize', 16, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.98 0.98 0.98], 'ForegroundColor', [0.2 0.2 0.7]);
    
    % 光栅类型选择
    gratingTypePanel = uipanel(parent, 'Title', '偏振光栅类型', ...
        'Position', [0.05, 0.7, 0.9, 0.25], 'FontSize', 12, ...
        'BackgroundColor', [0.98 0.98 0.98]);
    
    % 光栅类型列表
    gratingTypes = {
        '方形9点偏振光栅 - 基于Applied Optics期刊优化算法',
        '六边形9点偏振光栅 - 基于蜂窝结构优化',
        'Dammann偏振光栅 - 基于Optics Express期刊',
        'Fibonacci偏振光栅 - 超分辨率成像算法',
        'Pancharatnam-Berry相位光栅 - 几何相位',
        '聚合物稳定胆甾相光栅 - ESHFLC专用',
        '超材料型偏振光栅 - 创新设计'
    };
    
    uicontrol(gratingTypePanel, 'Style', 'listbox', ...
        'String', gratingTypes, 'Position', [20, 20, 800, 120], ...
        'FontSize', 10);
    
    % 公式显示区域
    formulaPanel = uipanel(parent, 'Title', '相关光学公式', ...
        'Position', [0.05, 0.35, 0.9, 0.3], 'FontSize', 12, ...
        'BackgroundColor', [0.98 0.98 0.98]);
    
    % 公式文本区域
    formulaText = sprintf(['基本衍射公式:\n\n', ...
        'sin(θ) = mλ/Λ  (光栅方程)\n', ...
        '其中: θ=衍射角, m=衍射级次, λ=波长, Λ=光栅周期\n\n', ...
        '偏振转换效率: η = sin²(πΔnd/λ)\n', ...
        '其中: Δn=双折射率差, d=厚度\n\n', ...
        '数值孔径: NA = n·sin(θ_max)\n', ...
        '分辨率: R = λ/(2·NA)']);
    
    uicontrol(formulaPanel, 'Style', 'text', ...
        'String', formulaText, ...
        'Position', [20, 20, 800, 140], 'FontSize', 11, ...
        'HorizontalAlignment', 'left', 'BackgroundColor', [0.98 0.98 0.98]);
end

function createSLMParamsTab(parent)
    % 创建SLM参数标签页
    
    % 标题
    uicontrol(parent, 'Style', 'text', 'String', 'SLM硬件参数与技术规格', ...
        'Position', [50, 720, 400, 30], 'FontSize', 16, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.98 0.98 0.98], 'ForegroundColor', [0.2 0.2 0.7]);
    
    % 硬件规格
    hardwarePanel = uipanel(parent, 'Title', 'SLM硬件技术规格', ...
        'Position', [0.05, 0.5, 0.4, 0.45], 'FontSize', 12, ...
        'BackgroundColor', [0.98 0.98 0.98]);
    
    hardwareText = sprintf(['SLM技术规格:\n\n', ...
        '显示技术: 液晶空间光调制器\n', ...
        '分辨率: 1920 × 1200 像素\n', ...
        '像素尺寸: 8.0 μm × 8.0 μm\n', ...
        '填充因子: > 95%%\n', ...
        '响应时间: < 20 ms\n', ...
        '工作波长: 400-700 nm\n', ...
        '相位调制范围: 0-2π\n', ...
        '偏振类型: 线性偏振\n', ...
        '驱动电压: 0-10V\n', ...
        '温度范围: 15-35°C\n', ...
        '接口类型: DVI/HDMI']);
    
    uicontrol(hardwarePanel, 'Style', 'text', 'String', hardwareText, ...
        'Position', [10, 10, 350, 280], 'FontSize', 10, ...
        'HorizontalAlignment', 'left', 'BackgroundColor', [0.98 0.98 0.98]);
    
    % 性能指标
    performancePanel = uipanel(parent, 'Title', '性能指标与特性', ...
        'Position', [0.5, 0.5, 0.45, 0.45], 'FontSize', 12, ...
        'BackgroundColor', [0.98 0.98 0.98]);
    
    performanceText = sprintf(['性能特性:\n\n', ...
        '衍射效率: > 90%%\n', ...
        '相位精度: λ/100\n', ...
        '均匀性: > 95%%\n', ...
        '对比度: > 1000:1\n', ...
        '稳定性: < 1%% (8小时)\n', ...
        '寿命: > 50000小时\n', ...
        '功耗: < 15W\n', ...
        '重量: < 2kg\n', ...
        '尺寸: 180×120×60 mm\n\n', ...
        'ESHFLC特性:\n', ...
        '切换时间: < 100 μs\n', ...
        '切换电压: 4-10V\n', ...
        '双稳态特性: 是']);
    
    uicontrol(performancePanel, 'Style', 'text', 'String', performanceText, ...
        'Position', [10, 10, 350, 280], 'FontSize', 10, ...
        'HorizontalAlignment', 'left', 'BackgroundColor', [0.98 0.98 0.98]);
end

function createExposureAnalysisTab(parent)
    % 创建曝光系统分析标签页
    
    % 标题
    uicontrol(parent, 'Style', 'text', 'String', '曝光系统光学分析', ...
        'Position', [50, 720, 400, 30], 'FontSize', 16, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.98 0.98 0.98], 'ForegroundColor', [0.2 0.2 0.7]);
    
    % 分析结果
    analysisPanel = uipanel(parent, 'Title', '系统性能分析结果', ...
        'Position', [0.05, 0.3, 0.9, 0.6], 'FontSize', 12, ...
        'BackgroundColor', [0.98 0.98 0.98]);
    
    % 分析文本
    analysisText = sprintf(['系统性能分析:\n\n', ...
        '光学分辨率: 2.5 μm\n', ...
        '数值孔径: 0.85\n', ...
        '景深: ±5 μm\n', ...
        '工作距离: 10 mm\n', ...
        '视场角: 15°\n', ...
        '照明均匀性: 95%%\n', ...
        '系统透过率: 85%%\n', ...
        '偏振纯度: > 99%%\n\n', ...
        '曝光参数:\n', ...
        '曝光时间: 0.1-10 s\n', ...
        '曝光功率: 1-100 mW/cm²\n', ...
        '重复精度: ±0.1 μm\n\n', ...
        '版权所有 © 个人Z.Y团队Y.M']);
    
    uicontrol(analysisPanel, 'Style', 'text', 'String', analysisText, ...
        'Position', [20, 20, 800, 350], 'FontSize', 11, ...
        'HorizontalAlignment', 'left', 'BackgroundColor', [0.98 0.98 0.98]);
    
    % 关闭按钮
    uicontrol(parent, 'Style', 'pushbutton', 'String', '关闭', ...
        'Position', [500, 50, 100, 30], ...
        'Callback', @(src,evt) close(gcbf), ...
        'FontWeight', 'bold', 'BackgroundColor', [0.3, 0.6, 0.9], ...
        'ForegroundColor', [1 1 1]);
end
